added defensive programming, UI feedback and error codes to hide/unhide

diff --git a/bin/git-hide b/bin/git-hide
--- a/bin/git-hide
+++ b/bin/git-hide
@@ -1,11 +1,64 @@
 #!/bin/bash
+# This command hides a branch, so that it does not display with the `git branch` command
 
-# TODO: check for params (exactly one branch name)
-# TODO: print usage if needed
-# TODO: check validity of input / is it a path
-# TODO: ensure that hiding a branch doesn't overwrite another of the same name
-# TODO: ensure that if hide fails, branch is not deleted
+# Exit codes
+EX_USAGE=3
+EX_MISSING_TARGET=4
+EX_DUPLICATE_HIDDEN=5
+EX_UPDATE_REF_FAILED_WITH_EC=6
+EX_UPDATE_REF_FAILED_NO_EC=7
+EX_DELETE_FAILED=8
+EX_DELETE_AND_CLEANUP_FAILED=9
+
+if [ $# -lt 2 ] || [ $# -gt 2] ; then
+	>&2 echo "usage: git hide branch-to-hide"
+	>&2 echo "This command hides a branch, so that it does not display with the 'git branch' command"
+	exit(EX_USAGE)
+fi
 
 branch=$1
+branchpath=$(git rev-parse --show-toplevel)/.git/refs/heads/$branch
+if [ ! test -e $branchpath ] ; then
+	>&2 echo "error: branch \"" $branch "\" not found heads"
+	exit(EX_MISSING_TARGET)
+fi
+
+hiddenpath=$(git rev-parse --show-toplevel)/.git/refs/hidden/$branch
+if [ test -e $hiddenpath ] ; then
+	>&2 echo "error: there is already a hidden branch with that name!"
+	exit(EX_DUPLICATE_HIDDEN)
+fi
+
+# copy branch to hidden folder
 git update-ref refs/hidden/$branch $branch
+if [ $? -ne 0 ] ; then
+	>&2 echo "error on update-ref: aborting hide command"
+	exit(EX_UPDATE_REF_FAILED_WITH_EC)
+fi
+
+if [ ! test -e $hiddenpath ] ; then
+	>&2 echo "error: hidden branch ref not found after update-ref, aborting hide command"
+	exit(EX_UPDATE_REF_FAILED_NO_EC)
+fi
+
+# delete original
 git branch -D $branch > /dev/null
+if [ $? -ne 0 ] ; then
+	>&2 echo "error: failed to delete original reference."
+	>&2 echo "aborting hide command. attempting to clean up..."
+	rm $hiddenpath
+	if [ test -e $hiddenpath ] ; then
+		>&2 echo "cleanup failed..."
+		exit(EX_DELETE_AND_CLEANUP_FAILED)
+	fi
+	# also delete all parent folders including hidden if empty
+	folders=hidden/$branch
+	while [ $(dirname $folders) -ne '.' ] ; do
+		folders=$(dirname $folders)
+		rmdir $folders > /dev/null 2> /dev/null
+		if [ $? -ne 0 ] ; then
+			break
+		fi
+	done
+	exit(EX_DELETE_FAILED)
+fi
diff --git a/bin/git-unhide b/bin/git-unhide
--- a/bin/git-unhide
+++ b/bin/git-unhide
@@ -1,11 +1,61 @@
 #!/bin/bash
+# This command reveals a previously hidden branch, so that it displays with the `git branch` command
 
-# TODO: check for params (exactly one branch name)
-# TODO: defensive logic: see hide
-# TODO: Check that this exists
+# Exit codes
+EX_USAGE=3
+EX_MISSING_TARGET=4
+EX_UPDATE_REF_FAILED_WITH_EC=6
+EX_UPDATE_REF_FAILED_NO_EC=7
+EX_DELETE_FAILED=8
+EX_NONE_HIDDEN=10
+EX_DUPLICATE_BRANCH=11
+
+if [ $# -lt 2 ] || [ $# -gt 2] ; then
+	>&2 echo "usage: git unhide branch-to-unhide"
+	>&2 echo "This command reveals a previously hidden branch, so that it displays with the 'git branch' command"
+	>&2 echo "Try 'git hidden' to see the names of hidden branches."
+	exit(EX_USAGE)
+fi
 
 branch=$1
-gitbasedir=$(git rev-parse --show-toplevel)
-githiddendir=$gitbasedir/.git/refs/hidden
-mkdir -p $githiddendir
+hidden_dir=$(git rev-parse --show-toplevel)/.git/refs/hidden/
+heads_dir=$(git rev-parse --show-toplevel)/.git/refs/heads/
+if [ ! test -e $hidden_dir ] ; then
+	>&2 echo "error: no hidden branches found"
+	exit(EX_NONE_HIDDEN)
+fi
+if [ ! test -e $hidden_dir$branch ] ; then
+	>&2 echo "error: branch \"" $branch "\" not found in hidden folder"
+	exit(EX_MISSING_TARGET)
+fi
+if [ test -e $heads_dir$branch ] ; then
+	>&2 echo "error: there is already an active branch with that name!"
+	exit(EX_DUPLICATE_BRANCH)
+fi
+
 git update-ref refs/heads/$branch refs/hidden/$branch
+if [ $? -ne 0 ] ; then
+	>&2 echo "error on update-ref: aborting unhide command"
+	exit(EX_UPDATE_REF_FAILED_WITH_EC)
+fi
+
+if [ ! test -e $heads_dir$branch ] ; then
+	>&2 echo "error: active branch ref not found after update-ref, aborting unhide command"
+	exit(EX_UPDATE_REF_FAILED_NO_EC)
+fi
+
+rm $hidden_dir$branch
+if [ $? -ne 0 ] ; then
+	>&2 echo "error: failed to delete hidden reference."
+	exit(EX_DELETE_FAILED)
+else
+	# clean up any unused hidden folders
+	folders=hidden/$branch
+	while [ $(dirname $folders) -ne '.' ] ; do
+		folders=$(dirname $folders)
+		rmdir $folders > /dev/null 2> /dev/null
+		if [ $? -ne 0 ] ; then
+			break
+		fi
+	done
+fi
