untested modifications following shellcheck and irc guidelines

diff --git a/bin/git-meld b/bin/git-meld
--- a/bin/git-meld
+++ b/bin/git-meld
@@ -31,10 +31,10 @@ do
 		branches_index=0
 		;;
 		--meld-force)
-		force_meld=true		
+		export force_meld=true
 		;;
 		--meld-quiet)
-		meld_quiet=true
+		export meld_quiet=true
 		;;
 		# collect all normal commands & flags
 		-*)
@@ -44,34 +44,34 @@ do
 		# collect the targets
 		args=$args' '$key
 		branches[$branches_index]=$key
-		>&/dev/null $((++branches_index))
+		(( ++branches_index ))
 		;;
 	esac
 	shift
 done
 
 # verify each branch exists and will not overwrite
-for branch in $branches ; do
-	if [ ! -e $(git rev-parse --show-toplevel)/.git/refs/heads/$branch ] ; then
-		if [ force_meld ] ; then
-			if [ ! meld_quiet ] ; then
-				>&2 echo "warning: no branch found for \""$branch"\"."
+for branch in "${branches[@]}" ; do
+	if [ ! -e "$(git rev-parse --show-toplevel)"/.git/refs/heads/"$branch" ] ; then
+		if [ $force_meld ] ; then
+			if [ ! $meld_quiet ] ; then
+				>&2 echo "warning: no branch found for \"$branch\"."
 			fi
 		else
-			>&2 echo "ERROR: No branch was found for \""$branch"\"."
+			>&2 echo "ERROR: No branch was found for \"$branch\"."
 			>&2 echo "hint: Use --meld-force to force."
 			exit $ec_missing_target
 		fi
 	fi
 	hiddenpath=$(git rev-parse --show-toplevel)/.git/refs/hidden/$branch
-	if [ -e $hiddenpath ] ; then
-		>&2 echo "ERROR: there is already a hidden branch with the name \""$branch"\" !"
-		>&2 echo "hint: To resolve manually relocate or delete \""$hiddenpath"\""
+	if [ -e "$hiddenpath" ] ; then
+		>&2 echo "ERROR: there is already a hidden branch with the name \"$branch\" !"
+		>&2 echo "hint: To resolve manually relocate or delete \"$hiddenpath\""
 			exit $ec_duplicate_hidden
 	fi
 done
 
-git merge --squash $args
+git merge --squash "$args"
 if [ $? -ne 0 ] ; then
 	>&2 echo "ERROR: The internal merge failed. To avoid damage, branches will remain visible."
 	>&2 echo "hint: You can hide them manually with 'git hide <branch>'."
@@ -79,7 +79,7 @@ if [ $? -ne 0 ] ; then
 	exit $ec_merge_failed
 fi
 
-for branch in $branches ; do
-	git hide $branch
+for branch in "${branches[@]}" ; do
+	git hide "$branch"
 done
 
diff --git a/bin/git-unhide b/bin/git-unhide
--- a/bin/git-unhide
+++ b/bin/git-unhide
@@ -24,40 +24,40 @@ fi
 branch=$1
 hidden_dir=$(git rev-parse --show-toplevel)/.git/refs/hidden/
 heads_dir=$(git rev-parse --show-toplevel)/.git/refs/heads/
-if [ ! -e $hidden_dir ] ; then
+if [ ! -e "$hidden_dir" ] ; then
 	>&2 echo "ERROR: no hidden branches found"
 	exit $ec_none_hidden
 fi
-if [ ! -e $hidden_dir$branch ] ; then
-	>&2 echo "ERROR: branch \""$branch"\" not found in hidden folder"
+if [ ! -e "$hidden_dir$branch" ] ; then
+	>&2 echo "ERROR: branch \"$branch\" not found in hidden folder"
 	exit $ec_missing_target
 fi
-if [ -e $heads_dir$branch ] ; then
-	>&2 echo "ERROR: there is already an active branch with the name \""$branch"\" !"
+if [ -e "$heads_dir$branch" ] ; then
+	>&2 echo "ERROR: there is already an active branch with the name \"$branch\" !"
 	exit $ec_duplicate_branch
 fi
 
-git update-ref refs/heads/$branch refs/hidden/$branch
+git update-ref refs/heads/"$branch" refs/hidden/"$branch"
 if [ $? -ne 0 ] ; then
-	>&2 echo "ERROR on update-ref: aborting unhide command for \""$branch"\""
+	>&2 echo "ERROR on update-ref: aborting unhide command for \"$branch\""
 	exit $ec_update_ref_failed_with_ec
 fi
 
-if [ ! -e $heads_dir$branch ] ; then
-	>&2 echo "ERROR: active branch ref not found after update-ref, aborting unhide command for \""$branch"\""
+if [ ! -e "$heads_dir$branch" ] ; then
+	>&2 echo "ERROR: active branch ref not found after update-ref, aborting unhide command for \"$branch\""
 	exit $ec_update_ref_failed_no_ec
 fi
 
-rm $hidden_dir$branch
+rm "$hidden_dir$branch"
 if [ $? -ne 0 ] ; then
-	>&2 echo "ERROR: failed to delete hidden reference for \""$branch"\""
+	>&2 echo "ERROR: failed to delete hidden reference for \"$branch\""
 	exit $ec_delete_failed
 else
 	# clean up any unused hidden folders
 	folders=hidden/$branch
-	while [ $(dirname $folders) != '.' ] ; do
-		folders=$(dirname $folders)
-		rmdir $(git rev-parse --show-toplevel)/.git/refs/$folders > /dev/null 2> /dev/null
+	while [ "$(dirname \"$folders\")" != '.' ] ; do
+		folders="$(dirname \"$folders\")"
+		rmdir "$(git rev-parse --show-toplevel)"/.git/refs/"$folders" > /dev/null 2> /dev/null
 		if [ $? -ne 0 ] ; then
 			break
 		fi
