Added safety checks and argument parsing to git-meld. Improved error messages.

diff --git a/bin/git-hide b/bin/git-hide
--- a/bin/git-hide
+++ b/bin/git-hide
@@ -23,32 +23,33 @@ fi
 branch=$1
 branchpath=$(git rev-parse --show-toplevel)/.git/refs/heads/$branch
 if [ ! test -e $branchpath ] ; then
-	>&2 echo "error: branch \"" $branch "\" not found heads"
+	>&2 echo "ERROR: branch \"" $branch "\" not found heads"
 	exit(EX_MISSING_TARGET)
 fi
 
 hiddenpath=$(git rev-parse --show-toplevel)/.git/refs/hidden/$branch
 if [ test -e $hiddenpath ] ; then
-	>&2 echo "error: there is already a hidden branch with that name!"
+	>&2 echo "ERROR: there is already a hidden branch with the name \"" $branch "\" !"
+	>&2 echo "To resolve manually relocate or delete \"" $hiddenpath "\""
 	exit(EX_DUPLICATE_HIDDEN)
 fi
 
 # copy branch to hidden folder
 git update-ref refs/hidden/$branch $branch
 if [ $? -ne 0 ] ; then
-	>&2 echo "error on update-ref: aborting hide command"
+	>&2 echo "ERROR on update-ref: aborting hide command"
 	exit(EX_UPDATE_REF_FAILED_WITH_EC)
 fi
 
 if [ ! test -e $hiddenpath ] ; then
-	>&2 echo "error: hidden branch ref not found after update-ref, aborting hide command"
+	>&2 echo "ERROR: hidden branch ref not found after update-ref, aborting hide command for \"" $branch "\""
 	exit(EX_UPDATE_REF_FAILED_NO_EC)
 fi
 
 # delete original
 git branch -D $branch > /dev/null
 if [ $? -ne 0 ] ; then
-	>&2 echo "error: failed to delete original reference."
+	>&2 echo "ERROR: failed to delete original reference for \"" $branch "\""
 	>&2 echo "aborting hide command. attempting to clean up..."
 	rm $hiddenpath
 	if [ test -e $hiddenpath ] ; then
diff --git a/bin/git-meld b/bin/git-meld
--- a/bin/git-meld
+++ b/bin/git-meld
@@ -5,13 +5,82 @@
 # Licensed under the Apache License, Version 2.0 (the "License");
 #     http://www.apache.org/licenses/LICENSE-2.0
 
-# TODO: ensure merge succeeds before hiding
-# TODO: make all the flags / params for merge work too!
-# TODO: use the git-hide command to do the hiding!
-# TODO: print good error messages
+# Exit codes
+EX_MISSING_TARGET=4
+EX_DUPLICATE_HIDDEN=5
+EX_MERGE_FAILED=12
 
-branch=$1
+args=${@:2}
 
-git merge --squash $branch
-git update-ref ref/hidden/$branch $branch
-git branch -D $branch
+branches_index=0
+
+consume_next_arg=false
+force_meld=false
+meld_quiet=false
+
+for arg in $args:
+do
+	if [ $consume_next_arg ] ; then
+		consume_next_arg=false
+		continue
+	fi
+
+	case $arg in
+		# prepare to consume flag argument in next iteration
+		-s|-X|-S|-m)
+		consume_next_arg=true
+		;;
+		# ignore leading message
+		HEAD)
+		unset branches
+		branches_index=0
+		;;
+		--meld-force)
+		force_meld=true		
+		;;
+		--meld-quiet)
+		meld_quiet=true
+		;;
+		# ignore all normal commands & flags
+		-*)
+		;;
+		*)
+		# collect the targets
+		branches[$branches_index]=arg
+		$((++branches_index))
+		;;
+	esac
+done
+
+for branch in $branches ; do
+	if [ ! file -e $(git rev-parse --show-toplevel)/.git/refs/heads/$branch ] ; do
+		if [ force_meld ] ; do
+			if [ ! meld_quiet ] ; do
+				>&2 echo "warning: no branch found for \"" $branch "\"."
+			fi
+		else
+			>&2 echo "ERROR: No branch was found for \"" $branch "\". Use --meld-force to force."
+			exit(EX_MISSING_TARGET)
+		fi
+	fi
+	hiddenpath=$(git rev-parse --show-toplevel)/.git/refs/hidden/$branch
+	if [ ! file -e $hiddenpath ] ; do
+		if [ test -e $hiddenpath ] ; then
+			>&2 echo "ERROR: there is already a hidden branch with the name \"" $branch "\" !"
+			>&2 echo "To resolve manually relocate or delete \"" $hiddenpath "\""
+			exit(EX_DUPLICATE_HIDDEN)
+		fi
+	fi
+done
+
+git merge --squash $args
+if [ $? -ne 0 ] ; then
+	>&2 echo "ERROR: The internal merge failed. To avoid damage, branches will remain visible."
+	>&2 echo "You can hide them manually with 'git hide <branch>'."
+	>&2 echo "You should verify the state of your project before proceeding."
+	exit(EX_MERGE_FAILED)
+else
+
+for branch in $branches ; do
+	git hide $branch
+done
diff --git a/bin/git-unhide b/bin/git-unhide
--- a/bin/git-unhide
+++ b/bin/git-unhide
@@ -25,32 +25,32 @@ branch=$1
 hidden_dir=$(git rev-parse --show-toplevel)/.git/refs/hidden/
 heads_dir=$(git rev-parse --show-toplevel)/.git/refs/heads/
 if [ ! test -e $hidden_dir ] ; then
-	>&2 echo "error: no hidden branches found"
+	>&2 echo "ERROR: no hidden branches found"
 	exit(EX_NONE_HIDDEN)
 fi
 if [ ! test -e $hidden_dir$branch ] ; then
-	>&2 echo "error: branch \"" $branch "\" not found in hidden folder"
+	>&2 echo "ERROR: branch \"" $branch "\" not found in hidden folder"
 	exit(EX_MISSING_TARGET)
 fi
 if [ test -e $heads_dir$branch ] ; then
-	>&2 echo "error: there is already an active branch with that name!"
+	>&2 echo "ERROR: there is already an active branch with the name \"" $branch "\" !"
 	exit(EX_DUPLICATE_BRANCH)
 fi
 
 git update-ref refs/heads/$branch refs/hidden/$branch
 if [ $? -ne 0 ] ; then
-	>&2 echo "error on update-ref: aborting unhide command"
+	>&2 echo "ERROR on update-ref: aborting unhide command for \"" $branch "\""
 	exit(EX_UPDATE_REF_FAILED_WITH_EC)
 fi
 
 if [ ! test -e $heads_dir$branch ] ; then
-	>&2 echo "error: active branch ref not found after update-ref, aborting unhide command"
+	>&2 echo "ERROR: active branch ref not found after update-ref, aborting unhide command for \"" $branch "\""
 	exit(EX_UPDATE_REF_FAILED_NO_EC)
 fi
 
 rm $hidden_dir$branch
 if [ $? -ne 0 ] ; then
-	>&2 echo "error: failed to delete hidden reference."
+	>&2 echo "ERROR: failed to delete hidden reference for \"" $branch "\""
 	exit(EX_DELETE_FAILED)
 else
 	# clean up any unused hidden folders
