robust-implementation-and-safety-features: it is working client-side.

diff --git a/bin/git-hide b/bin/git-hide
--- a/bin/git-hide
+++ b/bin/git-hide
@@ -1,11 +1,81 @@
 #!/bin/bash
+# This command hides a branch, so that it does not display with the `git branch` command
 
-# TODO: check for params (exactly one branch name)
-# TODO: print usage if needed
-# TODO: check validity of input / is it a path
-# TODO: ensure that hiding a branch doesn't overwrite another of the same name
-# TODO: ensure that if hide fails, branch is not deleted
+# Copyright 2015 by Jason Randolph Eads <jeads442@gmail.com>
+# Licensed under the Apache License, Version 2.0 (the "License");
+#     http://www.apache.org/licenses/LICENSE-2.0
+
+# Error codes thrown on exit
+ec_usage=3
+ec_missing_target=4
+ec_duplicate_hidden=5
+ec_update_ref_failed_with_ec=6
+ec_update_ref_failed_no_ec=7
+ec_delete_failed=8
+ec_delete_and_cleanup_failed=9
+
+if [ $# -ne 1 ] ; then
+	>&2 echo "usage: git hide branch-to-hide"
+	>&2 echo "This command hides a branch, so that it does not display with the 'git branch' command"
+	exit $ec_usage
+fi
 
 branch=$1
+branchpath=$(git rev-parse --show-toplevel)/.git/refs/heads/$branch
+if [ ! -e $branchpath ] ; then
+	>&2 echo "ERROR: branch \""$branch"\" not found in branch heads"
+	exit $ec_missing_target
+fi
+
+hiddenpath=$(git rev-parse --show-toplevel)/.git/refs/hidden/$branch
+if [ -e $hiddenpath ] ; then
+	>&2 echo "ERROR: there is already a hidden branch with the name \""$branch"\" !"
+	>&2 echo "To resolve manually relocate or delete \""$hiddenpath"\""
+	exit $ec_duplicate_hidden
+fi
+
+# copy branch to hidden folder
 git update-ref refs/hidden/$branch $branch
+if [ $? -ne 0 ] ; then
+	>&2 echo "ERROR on update-ref: aborting hide command"
+	exit $ec_update_ref_failed_with_ec
+fi
+
+if [ ! -e $hiddenpath ] ; then
+	>&2 echo "ERROR: hidden branch ref not found after update-ref, aborting hide command for \""$branch"\""
+	exit $ec_update_ref_failed_no_ec
+fi
+
+# delete original
 git branch -D $branch > /dev/null
+if [ $? -ne 0 ] ; then
+	>&2 echo "ERROR: failed to delete original reference for \""$branch"\""
+	>&2 echo "aborting hide command. attempting to clean up..."
+	rm $hiddenpath
+	if [ -e $hiddenpath ] ; then
+		>&2 echo "cleanup failed..."
+		exit $ec_delete_and_cleanup_failed
+	fi
+	# also delete all parent folders including hidden if empty
+	folders=hidden/$branch
+	echo folders $folders
+	while [ $(dirname $folders) != '.' ] ; do
+		folders=$(dirname $folders)
+		echo look
+		rmdir $folders > /dev/null 2> /dev/null
+		if [ $? -ne 0 ] ; then
+			break
+		fi
+	done
+	exit $ec_delete_failed
+else
+	# clean up any unused folders
+	folders=$branch
+	while [ $(dirname $folders) != '.' ] ; do
+		folders=$(dirname $folders)
+		rmdir $(git rev-parse --show-toplevel)/.git/refs/heads/$folders > /dev/null 2> /dev/null
+		if [ $? -ne 0 ] ; then
+			break
+		fi
+	done
+fi
diff --git a/bin/git-meld b/bin/git-meld
--- a/bin/git-meld
+++ b/bin/git-meld
@@ -1,12 +1,85 @@
 #!/bin/bash
+# This command melds the branch, like a squahed merge, then hides the associated branches
 
-# TODO: ensure merge succeeds before hiding
-# TODO: make all the flags / params for merge work too!
-# TODO: use the git-hide command to do the hiding!
-# TODO: print good error messages
+# Copyright 2015 by Jason Randolph Eads <jeads442@gmail.com>
+# Licensed under the Apache License, Version 2.0 (the "License");
+#     http://www.apache.org/licenses/LICENSE-2.0
 
-branch=$1
+# Error codes thrown on exit
+ec_missing_target=4
+ec_duplicate_hidden=5
+ec_merge_failed=12
 
-git merge --squash $branch
-git update-ref ref/hidden/$branch $branch
-git branch -D $branch
+branches_index=0
+
+force_meld=false
+meld_quiet=false
+
+while [[ $# -gt 0 ]]
+do
+	key="$1"
+	case $key in
+		# collect options and params
+		-s|-X|-S|-m)
+		args=$args' '$key
+		shift
+		args=$args' '$key
+		;;
+		# ignore leading message
+		HEAD)
+		unset branches
+		branches_index=0
+		;;
+		--meld-force)
+		force_meld=true		
+		;;
+		--meld-quiet)
+		meld_quiet=true
+		;;
+		# collect all normal commands & flags
+		-*)
+		args=$args' '$key
+		;;
+		*)
+		# collect the targets
+		args=$args' '$key
+		branches[$branches_index]=$key
+		>&/dev/null $((++branches_index))
+		;;
+	esac
+	shift
+done
+
+# verify each branch exists and will not overwrite
+for branch in $branches ; do
+	if [ ! -e $(git rev-parse --show-toplevel)/.git/refs/heads/$branch ] ; then
+		if [ force_meld ] ; then
+			if [ ! meld_quiet ] ; then
+				>&2 echo "warning: no branch found for \""$branch"\"."
+			fi
+		else
+			>&2 echo "ERROR: No branch was found for \""$branch"\"."
+			>&2 echo "hint: Use --meld-force to force."
+			exit $ec_missing_target
+		fi
+	fi
+	hiddenpath=$(git rev-parse --show-toplevel)/.git/refs/hidden/$branch
+	if [ -e $hiddenpath ] ; then
+		>&2 echo "ERROR: there is already a hidden branch with the name \""$branch"\" !"
+		>&2 echo "hint: To resolve manually relocate or delete \""$hiddenpath"\""
+			exit $ec_duplicate_hidden
+	fi
+done
+
+git merge --squash $args
+if [ $? -ne 0 ] ; then
+	>&2 echo "ERROR: The internal merge failed. To avoid damage, branches will remain visible."
+	>&2 echo "hint: You can hide them manually with 'git hide <branch>'."
+	>&2 echo "hint: You should verify the state of your project before proceeding."
+	exit $ec_merge_failed
+fi
+
+for branch in $branches ; do
+	git hide $branch
+done
+
diff --git a/bin/git-unhide b/bin/git-unhide
--- a/bin/git-unhide
+++ b/bin/git-unhide
@@ -1,11 +1,65 @@
 #!/bin/bash
+# This command restores a previously hidden branch
 
-# TODO: check for params (exactly one branch name)
-# TODO: defensive logic: see hide
-# TODO: Check that this exists
+# Copyright 2015 by Jason Randolph Eads <jeads442@gmail.com>
+# Licensed under the Apache License, Version 2.0 (the "License");
+#     http://www.apache.org/licenses/LICENSE-2.0
+
+# Error codes thrown on exit
+ec_usage=3
+ec_missing_target=4
+ec_update_ref_failed_with_ec=6
+ec_update_ref_failed_no_ec=7
+ec_delete_failed=8
+ec_none_hidden=10
+ec_duplicate_branch=11
+
+if [ $# -ne 1 ] ; then
+	>&2 echo "usage: git unhide branch-to-unhide"
+	>&2 echo "This command restores a previously hidden branch"
+	>&2 echo "Try 'git hidden' to see the names of hidden branches."
+	exit $ec_usage
+fi
 
 branch=$1
-gitbasedir=$(git rev-parse --show-toplevel)
-githiddendir=$gitbasedir/.git/refs/hidden
-mkdir -p $githiddendir
+hidden_dir=$(git rev-parse --show-toplevel)/.git/refs/hidden/
+heads_dir=$(git rev-parse --show-toplevel)/.git/refs/heads/
+if [ ! -e $hidden_dir ] ; then
+	>&2 echo "ERROR: no hidden branches found"
+	exit $ec_none_hidden
+fi
+if [ ! -e $hidden_dir$branch ] ; then
+	>&2 echo "ERROR: branch \""$branch"\" not found in hidden folder"
+	exit $ec_missing_target
+fi
+if [ -e $heads_dir$branch ] ; then
+	>&2 echo "ERROR: there is already an active branch with the name \""$branch"\" !"
+	exit $ec_duplicate_branch
+fi
+
 git update-ref refs/heads/$branch refs/hidden/$branch
+if [ $? -ne 0 ] ; then
+	>&2 echo "ERROR on update-ref: aborting unhide command for \""$branch"\""
+	exit $ec_update_ref_failed_with_ec
+fi
+
+if [ ! -e $heads_dir$branch ] ; then
+	>&2 echo "ERROR: active branch ref not found after update-ref, aborting unhide command for \""$branch"\""
+	exit $ec_update_ref_failed_no_ec
+fi
+
+rm $hidden_dir$branch
+if [ $? -ne 0 ] ; then
+	>&2 echo "ERROR: failed to delete hidden reference for \""$branch"\""
+	exit $ec_delete_failed
+else
+	# clean up any unused hidden folders
+	folders=hidden/$branch
+	while [ $(dirname $folders) != '.' ] ; do
+		folders=$(dirname $folders)
+		rmdir $(git rev-parse --show-toplevel)/.git/refs/$folders > /dev/null 2> /dev/null
+		if [ $? -ne 0 ] ; then
+			break
+		fi
+	done
+fi
