lot's of changes and debug on meld/hide/unhide. meld not finished, hide/unhide seem ok.

diff --git a/bin/git-hide b/bin/git-hide
--- a/bin/git-hide
+++ b/bin/git-hide
@@ -5,65 +5,77 @@
 # Licensed under the Apache License, Version 2.0 (the "License");
 #     http://www.apache.org/licenses/LICENSE-2.0
 
-# Exit codes
-EX_USAGE=3
-EX_MISSING_TARGET=4
-EX_DUPLICATE_HIDDEN=5
-EX_UPDATE_REF_FAILED_WITH_EC=6
-EX_UPDATE_REF_FAILED_NO_EC=7
-EX_DELETE_FAILED=8
-EX_DELETE_AND_CLEANUP_FAILED=9
+declare -a errorcodes
+errorcodes["usage_error"]=3
+errorcodes["missing_target"]=4
+errorcodes["duplicate_hidden"]=5
+errorcodes["update_ref_failed_EC"]=6
+errorcodes["update_ref_failed_no_EC"]=7
+errorcodes["delete_failed"]=8
+errorcodes["delete_and_cleanup_failed"]=9
 
-if [ $# -lt 2 ] || [ $# -gt 2] ; then
+if [ $# -ne 1 ] ; then
 	>&2 echo "usage: git hide branch-to-hide"
 	>&2 echo "This command hides a branch, so that it does not display with the 'git branch' command"
-	exit(EX_USAGE)
+	exit ${errorcodes["usage_error"]}
 fi
 
 branch=$1
 branchpath=$(git rev-parse --show-toplevel)/.git/refs/heads/$branch
-if [ ! test -e $branchpath ] ; then
-	>&2 echo "ERROR: branch \"" $branch "\" not found heads"
-	exit(EX_MISSING_TARGET)
+if [ ! -e $branchpath ] ; then
+	>&2 echo "ERROR: branch \""$branch"\" not found in branch heads"
+	exit ${errorcodes["missing_target"]}
 fi
 
 hiddenpath=$(git rev-parse --show-toplevel)/.git/refs/hidden/$branch
-if [ test -e $hiddenpath ] ; then
-	>&2 echo "ERROR: there is already a hidden branch with the name \"" $branch "\" !"
-	>&2 echo "To resolve manually relocate or delete \"" $hiddenpath "\""
-	exit(EX_DUPLICATE_HIDDEN)
+if [ -e $hiddenpath ] ; then
+	>&2 echo "ERROR: there is already a hidden branch with the name \""$branch"\" !"
+	>&2 echo "To resolve manually relocate or delete \""$hiddenpath"\""
+	exit ${errorcodes["duplicate_hidden"]}
 fi
 
 # copy branch to hidden folder
 git update-ref refs/hidden/$branch $branch
 if [ $? -ne 0 ] ; then
 	>&2 echo "ERROR on update-ref: aborting hide command"
-	exit(EX_UPDATE_REF_FAILED_WITH_EC)
+	exit ${errorcodes["update_ref_failed_EC"]}
 fi
 
-if [ ! test -e $hiddenpath ] ; then
-	>&2 echo "ERROR: hidden branch ref not found after update-ref, aborting hide command for \"" $branch "\""
-	exit(EX_UPDATE_REF_FAILED_NO_EC)
+if [ ! -e $hiddenpath ] ; then
+	>&2 echo "ERROR: hidden branch ref not found after update-ref, aborting hide command for \""$branch"\""
+	exit ${errorcodes["update_ref_failed_no_EC"]}
 fi
 
 # delete original
 git branch -D $branch > /dev/null
 if [ $? -ne 0 ] ; then
-	>&2 echo "ERROR: failed to delete original reference for \"" $branch "\""
+	>&2 echo "ERROR: failed to delete original reference for \""$branch"\""
 	>&2 echo "aborting hide command. attempting to clean up..."
 	rm $hiddenpath
-	if [ test -e $hiddenpath ] ; then
+	if [ -e $hiddenpath ] ; then
 		>&2 echo "cleanup failed..."
-		exit(EX_DELETE_AND_CLEANUP_FAILED)
+		exit ${errorcodes["delete_and_cleanup_failed"]}
 	fi
 	# also delete all parent folders including hidden if empty
 	folders=hidden/$branch
-	while [ $(dirname $folders) -ne '.' ] ; do
+	echo folders $folders
+	while [ $(dirname $folders) != '.' ] ; do
 		folders=$(dirname $folders)
+		echo look
 		rmdir $folders > /dev/null 2> /dev/null
 		if [ $? -ne 0 ] ; then
 			break
 		fi
 	done
-	exit(EX_DELETE_FAILED)
+	exit ${errorcodes["delete_failed"]}
+else
+	# clean up any unused folders
+	folders=$branch
+	while [ $(dirname $folders) != '.' ] ; do
+		folders=$(dirname $folders)
+		rmdir $(git rev-parse --show-toplevel)/.git/refs/heads/$folders > /dev/null 2> /dev/null
+		if [ $? -ne 0 ] ; then
+			break
+		fi
+	done
 fi
diff --git a/bin/git-meld b/bin/git-meld
--- a/bin/git-meld
+++ b/bin/git-meld
@@ -5,30 +5,27 @@
 # Licensed under the Apache License, Version 2.0 (the "License");
 #     http://www.apache.org/licenses/LICENSE-2.0
 
-# Exit codes
-EX_MISSING_TARGET=4
-EX_DUPLICATE_HIDDEN=5
-EX_MERGE_FAILED=12
-
-args=${@:2}
+declare -a errorcodes
+errorcodes["missing_target"]=4
+errorcodes["duplicate_hidden"]=5
+errorcodes["merge_failed"]=12
 
 branches_index=0
 
-consume_next_arg=false
 force_meld=false
 meld_quiet=false
 
-for arg in $args:
-do
-	if [ $consume_next_arg ] ; then
-		consume_next_arg=false
-		continue
-	fi
+echo $@
 
-	case $arg in
-		# prepare to consume flag argument in next iteration
+while [[ $# -gt 0 ]]
+do
+	key="$1"
+	case $key in
+		# collect options and params
 		-s|-X|-S|-m)
-		consume_next_arg=true
+		args=$args' '$key
+		shift
+		args=$args' '$key
 		;;
 		# ignore leading message
 		HEAD)
@@ -41,45 +38,47 @@ do
 		--meld-quiet)
 		meld_quiet=true
 		;;
-		# ignore all normal commands & flags
+		# collect all normal commands & flags
 		-*)
+		args=$args' '$key
 		;;
 		*)
 		# collect the targets
 		branches[$branches_index]=arg
-		$((++branches_index))
+		>&/dev/null $((++branches_index))
 		;;
 	esac
+	shift
 done
 
 for branch in $branches ; do
-	if [ ! file -e $(git rev-parse --show-toplevel)/.git/refs/heads/$branch ] ; do
-		if [ force_meld ] ; do
-			if [ ! meld_quiet ] ; do
-				>&2 echo "warning: no branch found for \"" $branch "\"."
+	if [ ! -e $(git rev-parse --show-toplevel)/.git/refs/heads/$branch ] ; then
+		if [ force_meld ] ; then
+			if [ ! meld_quiet ] ; then
+				>&2 echo "warning: no branch found for \""$branch"\"."
 			fi
 		else
-			>&2 echo "ERROR: No branch was found for \"" $branch "\". Use --meld-force to force."
-			exit(EX_MISSING_TARGET)
+			>&2 echo "ERROR: No branch was found for \""$branch"\"."
+			>&2 echo "hint: Use --meld-force to force."
+			exit ${errorcodes["missing_target"]}
 		fi
 	fi
 	hiddenpath=$(git rev-parse --show-toplevel)/.git/refs/hidden/$branch
-	if [ ! file -e $hiddenpath ] ; do
-		if [ test -e $hiddenpath ] ; then
-			>&2 echo "ERROR: there is already a hidden branch with the name \"" $branch "\" !"
-			>&2 echo "To resolve manually relocate or delete \"" $hiddenpath "\""
-			exit(EX_DUPLICATE_HIDDEN)
-		fi
+	if [ -e $hiddenpath ] ; then
+		>&2 echo "ERROR: there is already a hidden branch with the name \""$branch"\" !"
+		>&2 echo "hint: To resolve manually relocate or delete \""$hiddenpath"\""
+		exit ${errorcodes["duplicate_hidden"]}
 	fi
 done
 
-git merge --squash $args
+echo $args
+git merge --squash $args $
 if [ $? -ne 0 ] ; then
 	>&2 echo "ERROR: The internal merge failed. To avoid damage, branches will remain visible."
-	>&2 echo "You can hide them manually with 'git hide <branch>'."
-	>&2 echo "You should verify the state of your project before proceeding."
-	exit(EX_MERGE_FAILED)
-else
+	>&2 echo "hint: You can hide them manually with 'git hide <branch>'."
+	>&2 echo "hint: You should verify the state of your project before proceeding."
+	exit ${errorcodes["merge_failed"]}
+fi
 
 for branch in $branches ; do
 	git hide $branch
diff --git a/bin/git-unhide b/bin/git-unhide
--- a/bin/git-unhide
+++ b/bin/git-unhide
@@ -5,59 +5,59 @@
 # Licensed under the Apache License, Version 2.0 (the "License");
 #     http://www.apache.org/licenses/LICENSE-2.0
 
-# Exit codes
-EX_USAGE=3
-EX_MISSING_TARGET=4
-EX_UPDATE_REF_FAILED_WITH_EC=6
-EX_UPDATE_REF_FAILED_NO_EC=7
-EX_DELETE_FAILED=8
-EX_NONE_HIDDEN=10
-EX_DUPLICATE_BRANCH=11
+declare -a errorcodes
+errorcodes["usage_error"]=3
+errorcodes["missing_target"]=4
+errorcodes["update_ref_failed_EC"]=6
+errorcodes["update_ref_failed_no_EC"]=7
+errorcodes["delete_failed"]=8
+errorcodes["none_hidden"]=10
+errorcodes["duplicate_branch"]=11
 
-if [ $# -lt 2 ] || [ $# -gt 2] ; then
+if [ $# -ne 1 ] ; then
 	>&2 echo "usage: git unhide branch-to-unhide"
 	>&2 echo "This command restores a previously hidden branch"
 	>&2 echo "Try 'git hidden' to see the names of hidden branches."
-	exit(EX_USAGE)
+	exit ${errorcodes["usage_error"]}
 fi
 
 branch=$1
 hidden_dir=$(git rev-parse --show-toplevel)/.git/refs/hidden/
 heads_dir=$(git rev-parse --show-toplevel)/.git/refs/heads/
-if [ ! test -e $hidden_dir ] ; then
+if [ ! -e $hidden_dir ] ; then
 	>&2 echo "ERROR: no hidden branches found"
-	exit(EX_NONE_HIDDEN)
+	exit ${errorcodes["none_hidden"]}
 fi
-if [ ! test -e $hidden_dir$branch ] ; then
-	>&2 echo "ERROR: branch \"" $branch "\" not found in hidden folder"
-	exit(EX_MISSING_TARGET)
+if [ ! -e $hidden_dir$branch ] ; then
+	>&2 echo "ERROR: branch \""$branch"\" not found in hidden folder"
+	exit ${errorcodes["missing_target"]}
 fi
-if [ test -e $heads_dir$branch ] ; then
-	>&2 echo "ERROR: there is already an active branch with the name \"" $branch "\" !"
-	exit(EX_DUPLICATE_BRANCH)
+if [ -e $heads_dir$branch ] ; then
+	>&2 echo "ERROR: there is already an active branch with the name \""$branch"\" !"
+	exit ${errorcodes["duplicate_branch"]}
 fi
 
 git update-ref refs/heads/$branch refs/hidden/$branch
 if [ $? -ne 0 ] ; then
-	>&2 echo "ERROR on update-ref: aborting unhide command for \"" $branch "\""
-	exit(EX_UPDATE_REF_FAILED_WITH_EC)
+	>&2 echo "ERROR on update-ref: aborting unhide command for \""$branch"\""
+	exit ${errorcodes["update_ref_failed_EC"]}
 fi
 
-if [ ! test -e $heads_dir$branch ] ; then
-	>&2 echo "ERROR: active branch ref not found after update-ref, aborting unhide command for \"" $branch "\""
-	exit(EX_UPDATE_REF_FAILED_NO_EC)
+if [ ! -e $heads_dir$branch ] ; then
+	>&2 echo "ERROR: active branch ref not found after update-ref, aborting unhide command for \""$branch"\""
+	exit ${errorcodes["update_ref_failed_no_EC"]}
 fi
 
 rm $hidden_dir$branch
 if [ $? -ne 0 ] ; then
-	>&2 echo "ERROR: failed to delete hidden reference for \"" $branch "\""
-	exit(EX_DELETE_FAILED)
+	>&2 echo "ERROR: failed to delete hidden reference for \""$branch"\""
+	exit ${errorcodes["delete_failed"]}
 else
 	# clean up any unused hidden folders
 	folders=hidden/$branch
-	while [ $(dirname $folders) -ne '.' ] ; do
+	while [ $(dirname $folders) != '.' ] ; do
 		folders=$(dirname $folders)
-		rmdir $folders > /dev/null 2> /dev/null
+		rmdir $(git rev-parse --show-toplevel)/.git/refs/$folders > /dev/null 2> /dev/null
 		if [ $? -ne 0 ] ; then
 			break
 		fi
